version: '3'

services:
  webapp:
    build:
      context: ./webapp
    container_name: webapp
    volumes:
      - ./webapp:/usr/src/app
    entrypoint: wait-for mysql:3306 -t 30 -- sh -c "npm install && node index.js"
    networks:
      - development
    depends_on:
      - mysql

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - '8080:80'
    depends_on:
      - webapp
    networks:
      - development

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - development
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local

networks:
  development:
    driver: bridge
